apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xmkn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xmkn
    app.kubernetes.io/part-of: ci1t-43256-0036-app
  name: devfile-sample-xmkn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xmkn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xmkn
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0036-tenant/ci1t-43256-0036-app/devfile-sample-xmkn@sha256:e6e42cb43e421c4cb098d7e8ef15852685448de3d1d689ce33cc3f7e3c21580c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
